/** Parameters of the fractal generator */
enum FractalGeneratorParameters {
  DIMENSION_RATIO = "DIMENSION_RATIO",
  COORDINATES_SCALE = "COORDINATES_SCALE",
  COORDINATES_CENTRE = "COORDINATES_CENTRE",

  TIME = "TIME",

  IS_NEWTON = "IS_NEWTON",
  NUMERATOR_COEFFICIENTS_COUNT = "NUMERATOR_COEFFICIENTS_COUNT",
  DENOMINATOR_COEFFICIENTS_COUNT = "DENOMINATOR_COEFFICIENTS_COUNT",
  NEWTON_COEFFICIENT = "NEWTON_COEFFICIENT",

  NUMERATOR = "NUMERATOR",
  DENOMINATOR = "DENOMINATOR",

  ITERATIONS_COUNT = "ITERATIONS_COUNT",
  EPSILON = "EPSILON",
  JULIA_BOUND = "JULIA_BOUND",
  JULIA_HSV = "JULIA_HSV",
  DEFAULT_COLOUR = "DEFAULT_COLOUR",
  INFINITY_COLOUR = "INFINITY_COLOUR",
  ATTRACTORS_COUNT = "ATTRACTORS_COUNT",
  ATTRACTORS = "ATTRACTORS",
}
export default FractalGeneratorParameters;
