/** Parameters of the fractal generator */
enum FractalGeneratorParameters {
  DIMENSION_RATIO = "DIMENSION_RATIO",
  COORDINATES_SCALE = "COORDINATES_SCALE",
  COORDINATES_CENTRE = "COORDINATES_CENTRE",

  TIME = "TIME",

  IS_NEWTON = "IS_NEWTON",
  NUMERATOR_COEFFICIENTS_COUNT = "NUMERATOR_COEFFICIENTS_COUNT",
  DENOMINATOR_COEFFICIENTS_COUNT = "DENOMINATOR_COEFFICIENTS_COUNT",
  NEWTON_COEFFICIENT = "NEWTON_COEFFICIENT",

  NUMERATOR = "NUMERATOR",
  DENOMINATOR = "DENOMINATOR",

  ITERATIONS_COUNT = "ITERATIONS_COUNT",
  EPSILON = "EPSILON",
  JULIA_BOUND = "JULIA_BOUND",
  FATOU_HUE = "FATOU_HUE",
  FATOU_SATURATION_STRENGTH = "FATOU_SATURATION_STRENGTH",
  FATOU_SATURATION_OFFSET = "FATOU_SATURATION_OFFSET",
  FATOU_VALUE_STRENGTH = "FATOU_VALUE_STRENGTH",
  FATOU_VALUE_OFFSET = "FATOU_VALUE_OFFSET",
  JULIA_HSV = "JULIA_HSV",
}
export default FractalGeneratorParameters;
