export const DIMENSION_RATIO = "DIMENSION_RATIO";
export const COORDINATES_SCALE = "COORDINATES_SCALE";
export const COORDINATES_CENTRE = "COORDINATES_CENTRE";
export const TIME = "TIME";
export const IS_NEWTON = "IS_NEWTON";
export const NUMERATOR_COEFFICIENTS_COUNT = "NUMERATOR_COEFFICIENTS_COUNT";
export const DENOMINATOR_COEFFICIENTS_COUNT = "DENOMINATOR_COEFFICIENTS_COUNT";
export const NEWTON_COEFFICIENT = "NEWTON_COEFFICIENT";
export const NUMERATOR = "NUMERATOR";
export const DENOMINATOR = "DENOMINATOR";
export const ITERATIONS_COUNT = "ITERATIONS_COUNT";
export const EPSILON = "EPSILON";
export const JULIA_BOUND = "JULIA_BOUND";
export const FATOU_HUE = "FATOU_HUE";
export const FATOU_SATURATION_STRENGTH = "FATOU_SATURATION_STRENGTH";
export const FATOU_SATURATION_OFFSET = "FATOU_SATURATION_OFFSET";
export const FATOU_VALUE_STRENGTH = "FATOU_VALUE_STRENGTH";
export const FATOU_VALUE_OFFSET = "FATOU_VALUE_OFFSET";
export const JULIA_HSV = "JULIA_HSV";

export const FRACTAL_GENERATOR_PARAMETERS = {
  DIMENSION_RATIO,
  COORDINATES_SCALE,
  COORDINATES_CENTRE,
  TIME,
  IS_NEWTON,
  NUMERATOR_COEFFICIENTS_COUNT,
  DENOMINATOR_COEFFICIENTS_COUNT,
  NEWTON_COEFFICIENT,
  NUMERATOR,
  DENOMINATOR,
  ITERATIONS_COUNT,
  EPSILON,
  JULIA_BOUND,
  FATOU_HUE,
  FATOU_SATURATION_STRENGTH,
  FATOU_SATURATION_OFFSET,
  FATOU_VALUE_STRENGTH,
  FATOU_VALUE_OFFSET,
  JULIA_HSV,
} as const;

export type FractalGeneratorParameter =
  (typeof FRACTAL_GENERATOR_PARAMETERS)[keyof typeof FRACTAL_GENERATOR_PARAMETERS];
